# Header
menu:
  Home: /
  Posts: /archives
  Menu: /menu

# Content
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname: ivsitehexo

# Widgets List
widgets:
  about: This blog is based off the official bootstrap blog template.
  tags: true
  category: true